spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/monster?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/,classpath:/static/layui-v2.5.3/layui,classpath:/static/layui-v2.5.3/layui/css,classpath:/D:/uploads/sb/,classpath:/D:/uploads/sb,
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql: true
    database: mysql
mybatis:
  type-aliases-package: com.oac.sbdemo.domain
server:
  port: 996

#上传文件
upload:
    location:
      windows: E:\uploads\sb\
      linux: /usr/etc/uploads/




