spring:
  datasource:
    url: jdbc:mysql://www.majorjava.com/monster?useUnicode=true&characterEncoding=utf-8
    username: root
    password: zhutengfei
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql: true
    database: mysql
mybatis:
  type-aliases-package: com.oac.sbdemo.domain



